-- MySQL Script generated by MySQL Workbench
-- Sun Jun 30 23:19:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cooperSystemEcommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cooperSystemEcommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cooperSystemEcommerce` DEFAULT CHARACTER SET utf8 ;
USE `cooperSystemEcommerce` ;

-- -----------------------------------------------------
-- Table `cooperSystemEcommerce`.`tb_situacao_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperSystemEcommerce`.`tb_situacao_produto` (
  `idSituacao` INT NOT NULL AUTO_INCREMENT,
  `situacaoProduto` VARCHAR(45) NULL,
  PRIMARY KEY (`idSituacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperSystemEcommerce`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperSystemEcommerce`.`tb_produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProd` VARCHAR(45) NOT NULL,
  `valorProd` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NOT NULL DEFAULT 0,
  `tb_situacao_produto_idSituacao` INT NOT NULL,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_tb_produto_tb_situacao_produto_idx` (`tb_situacao_produto_idSituacao` ASC),
  CONSTRAINT `fk_tb_produto_tb_situacao_produto`
    FOREIGN KEY (`tb_situacao_produto_idSituacao`)
    REFERENCES `cooperSystemEcommerce`.`tb_situacao_produto` (`idSituacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperSystemEcommerce`.`tb_situacao_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperSystemEcommerce`.`tb_situacao_pedido` (
  `idSituacao_pedido` INT NOT NULL AUTO_INCREMENT,
  `situacaoPedido` VARCHAR(45) NULL,
  PRIMARY KEY (`idSituacao_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperSystemEcommerce`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperSystemEcommerce`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `enderecoUsr` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperSystemEcommerce`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperSystemEcommerce`.`tb_pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `solicitante` VARCHAR(100) NOT NULL,
  `despachante` VARCHAR(100) NOT NULL,
  `tb_situacao_pedido_idSituacao_pedido` INT NOT NULL,
  `users_id` BIGINT(20) NOT NULL,
  `valor_total_pedido` DECIMAL(15,2) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_tb_pedido_tb_situacao_pedido1_idx` (`tb_situacao_pedido_idSituacao_pedido` ASC),
  INDEX `fk_tb_pedido_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_tb_pedido_tb_situacao_pedido1`
    FOREIGN KEY (`tb_situacao_pedido_idSituacao_pedido`)
    REFERENCES `cooperSystemEcommerce`.`tb_situacao_pedido` (`idSituacao_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cooperSystemEcommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooperSystemEcommerce`.`tb_produtos_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooperSystemEcommerce`.`tb_produtos_pedido` (
  `tb_produto_idProduto` INT NOT NULL,
  `tb_pedido_idPedido` INT NOT NULL,
  `quantidade_individual` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_tb_produtos_pedido_tb_produto1_idx` (`tb_produto_idProduto` ASC),
  INDEX `fk_tb_produtos_pedido_tb_pedido1_idx` (`tb_pedido_idPedido` ASC),
  CONSTRAINT `fk_tb_produtos_pedido_tb_produto1`
    FOREIGN KEY (`tb_produto_idProduto`)
    REFERENCES `cooperSystemEcommerce`.`tb_produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_pedido_tb_pedido1`
    FOREIGN KEY (`tb_pedido_idPedido`)
    REFERENCES `cooperSystemEcommerce`.`tb_pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cooperSystemEcommerce`.`tb_situacao_produto`
-- -----------------------------------------------------
START TRANSACTION;
USE `cooperSystemEcommerce`;
INSERT INTO `cooperSystemEcommerce`.`tb_situacao_produto` (`idSituacao`, `situacaoProduto`) VALUES (1, 'Disponível');
INSERT INTO `cooperSystemEcommerce`.`tb_situacao_produto` (`idSituacao`, `situacaoProduto`) VALUES (2, 'Indisponível');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cooperSystemEcommerce`.`tb_situacao_pedido`
-- -----------------------------------------------------
START TRANSACTION;
USE `cooperSystemEcommerce`;
INSERT INTO `cooperSystemEcommerce`.`tb_situacao_pedido` (`idSituacao_pedido`, `situacaoPedido`) VALUES (1, 'Pendente de Envio');
INSERT INTO `cooperSystemEcommerce`.`tb_situacao_pedido` (`idSituacao_pedido`, `situacaoPedido`) VALUES (2, 'Enviado');
INSERT INTO `cooperSystemEcommerce`.`tb_situacao_pedido` (`idSituacao_pedido`, `situacaoPedido`) VALUES (3, 'Entregue');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cooperSystemEcommerce`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `cooperSystemEcommerce`;
INSERT INTO `cooperSystemEcommerce`.`users` (`id`, `name`, `email`, `password`, `created_at`, `updated_at`, `enderecoUsr`) VALUES (1, 'demo', 'demo@coopersystem.com', '$2y$10$rm4z/2Uu612UzYzAROU.puKObgLQqhDUKQOL5/VDthSgja9ZN8Oai', '2019-06-30 00:49:43', '2019-06-30 00:49:43', NULL);

COMMIT;
